version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: [
      '--bind-address=0.0.0.0',
      '--skip-name-resolve',
      '--default-authentication-plugin=mysql_native_password'
    ]
    container_name: mysql_todo
    environment:
      - MYSQL_DATABASE=${APP_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - backend_net

  springboot-app:
    build: .
    env_file: .env
    container_name: springboot_todo
    ports:
      - "${SERVER_PORT}:8081"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS}
      - APP_NAME=${APP_NAME}
    networks:
      - backend_net

volumes:
  mysql_data:

networks:
  backend_net:
    driver: bridge